project:
  id: "2025_BA"
  name: "2025_bachelor_thesis"

experiment:
  id: "2023_plesse"
  name: "2023_treecable_plesse_v1"

paths:
  data: "../../200_data"
  working: "working"
  results:
    root: "../../400_results/2023_treecable_plesse_v1"
    plots: "plots"
    tables: "tables"
    reports: "reports"
    logs: "logs"
    exports: "exports"
    latex: "latex"
  notebooks: "notebooks"
  scripts: "scripts"

devices:
  use_metadata: true
  use_ls3: true
  use_ptq: true
  use_tms: false
  use_tcc: false
